[metadata]
name = barbican-ui
summary = OpenStack Key Manager (Barbican) UI panel for Horizon
description-file = README.rst
author = OpenStack
author-email = openstack-discuss@lists.openstack.org
home-page = https://opendev.org/openstack/barbican-ui

[files]
packages =
    barbican_ui

[entry_points]
openstack_dashboard_config =
    enabled = barbican_ui.enabled

[options]
python_requires = >=3.9


[pbr]
warnerrors = True

[wheel]
universal = 1

[tool:pytest]
testpaths = barbican_ui/test
