[tox]
minversion = 3.18.0
envlist = py39,py310,py311,pep8,cover
skipsdist = False

[testenv]
usedevelop = True
install_command = pip install -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master} {opts} {packages}
setenv =
    VIRTUAL_ENV={envdir}
    DJANGO_SETTINGS_MODULE=barbican_ui.test.settings
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
commands =
    python manage.py test barbican_ui.test --settings=barbican_ui.test.settings {posargs}

[testenv:pep8]
commands =
    flake8 {posargs}

[testenv:cover]
setenv =
    {[testenv]setenv}
    PYTHON=coverage run --source barbican_ui --parallel-mode
commands =
    coverage erase
    python manage.py test barbican_ui.test --settings=barbican_ui.test.settings {posargs}
    coverage combine
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report --fail-under=60

[testenv:venv]
commands = {posargs}

[testenv:docs]
deps =
    -r{toxinidir}/requirements.txt
    sphinx>=2.0.0
    openstackdocstheme>=2.3.0
commands =
    sphinx-build -a -E -W -d doc/build/doctrees -b html doc/source doc/build/html

[flake8]
# E123, E125 skipped as they are not PEP8 compliant
show-source = True
ignore = E123,E125,W504
builtins = _
exclude = .venv,.git,.tox,dist,doc,*lib/python*,*egg,build,.ropeproject

[coverage:run]
source = barbican_ui
omit =
    barbican_ui/test/*
    barbican_ui/migrations/*
